custom:
  jwt:
    secretPattern: abcdedffghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890
  oauth2:
    kakao:
      clientId: 5013d6bbf3bacda64d1884301a0a8000

# 강사님꺼 KAKAO_CLIENT_ID=8c54de56d650fa230db6eb5134313c23